services:
  app:
    # Build time, parameters come always from .env
    build:
      context: .
      dockerfile: Dockerfile
    # Runtime outside container, parameters come always from .env 
    # Environment variables set here are ony available in Runtime inside container
    restart: no
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    env_file: # defaults to .env
      - .env
    environment: # overrrides env_file variables
      - ENV=development
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app
    command:
